numero1 = int(input('Dame el 1er número: '))
numero2 = int(input('Dame el 2do número: '))
print(f'La Suma es: {numero1+numero2}')
print(f'La Resta es: {numero1-numero2}')
print(f'La Multiplicación es: {numero1*numero2}')
print(f'La División es: {numero1/numero2}')